### ISSUE TITLE
Question: Pretrained Model

### ISSUE THREAD

**Issue by ndisci** [Audio-WestlakeU/McNet#1]
Hi, 

Thanks for the work. I am curious about pretrained model. Will you released your pretrained model or not?

**Comment by Yang-yujie** [comment]
Hi~, 
Thanks for your question. We will release our pretrained model soon and update the document simultaneously.

**Comment by ndisci** [comment]
Thanks a lot. I'm looking forward to your updates.

**Comment by Yang-yujie** [comment]
We upload our pretrained model and update the document today. 
And if you like our work, could you please give us a thumbs-up? : )

**Comment by ndisci** [comment]
Thanks ! When I used the pretrained model  I got  adapt_kwargs_n = {**adapt_kwargs, 'prev_val': prev_val[n]} if isinstance(prev_val, list) else adapt_kwargs IndexError: list index out of range
I follow readme :
python McNetCLI.py test --config config/mc_net_offline.yaml  --trainer.gpus 0  --ckpt_path model_checkpoints/offline/epoch494_criteria18.78_sdr18.78.ckpt

What's your omegaconf and pytorch version ?
