### ISSUE TITLE
McNet layers and McNetIO

### ISSUE THREAD

**Issue by ndisci** [Audio-WestlakeU/McNet#3]
Thanks for the pretrained model ! When I load model from checkpoint I see io channel from 0 to 5. What does it mean ? 
How can I use checkpoint for an audio file for prediction( only enhancement ) ? 
Could you explain model forward also?

**Comment by quancs** [comment]
Sorry for the late reply.

> When I load model from checkpoint I see io channel from 0 to 5. What does it mean ?

It means the microphone channels used.

> How can I use checkpoint for an audio file for prediction( only enhancement ) ? Could you explain model forward also?

You can load the module first, then call the [predict_step](https://github.com/Audio-WestlakeU/McNet/blob/db37cb1efaa5e647bc31bdb38bc32266df7fbd02/src/model/mc_net.py#L603).

**Comment by Yang-yujie** [comment]
We update this repository. Now you can load a checkpoint and use it to predict any audio you want. But one thing that needs to be noticed is if you use six-channel data to train the model, you can only feed this network a six-channel audio file for prediction.
