### ISSUE TITLE
使用其他数据集进行训练

### ISSUE THREAD

**Issue by enlunox** [Audio-WestlakeU/McNet#5]
你好，我想使用其他数据集的多个单通语音来作为模型多通道的输入进行训练，但代码(config/.yaml)中noisy_dataset_dir只有一个路径。
请问noisy data是用何种方式来进行存取？建议如何修改代码？

**Comment by wrz1999** [comment]
同问

**Comment by Yang-yujie** [comment]
不太理解，你说的多个单通道语音作为训练，是把多通道的语音按照不同的通道存了下来，还是什么意思？
如果你要改data的读取，请你修改src/dataset/my_data_module.py，以及对应train_dataset.py, val_dataset.py，inf_dataset.py, predict_dataset.py。
