### ISSUE TITLE
关于数据集的预处理问题

### ISSUE THREAD

**Issue by XiangzhuKong** [Audio-WestlakeU/McNet#7]
您好，我看程序中使用数据集的路径和原始的CHiME-4数据集结构似乎不太相同，请问在拿到CHiME-4数据集后是需要进行下预处理吗？可以提供下训练时使用的数据集结构和处理程序嘛？谢谢！如果能有说明的话就更好了 ：）

**Comment by Yang-yujie** [comment]
您好，不好意思才看到您的问题，希望下列的回答对您有帮助：
1. 语音部分的数据：在训练的过程中，我们使用的多通道干净语音，可以通过CHIME提供的tools/simulation/CHIME3_simulate_data.m的代码生成，代码中默认只保存了带噪的语音，需要你修改一下原本的代码，将干净的语音保存下来，因为我们的训练过程是采用动态的混合噪声的方式合成带噪语音的。其余预处理过程就只有将CHIME提供的多个单通道的语音合成了一个多通道的WAV，以方便读取。
2. 噪声部分的数据：我们将CHIME提供的长达半个小时的噪声片段，裁剪成了16s左右的固定长度的噪声片段，以方便读取，当然在裁剪的过程中我们采用了overlap的方式，也就是前后两个裁剪后的噪声段是有重叠的，重叠率是50%，这样在动态混合噪声的过程中可以尽可能多利用原有的噪声。并且，对于噪声，我们也将原先CHIME单个通道的噪声片段合并成多通道的WAV文件。

**Comment by Yang-yujie** [comment]
组织的数据集结构如下：
simu-data
├── test_dataset
│   ├── clean
│   │   ├── F05_440C0202_BUS.wav
│   │   ├── F05_440C0202_CAF.wav
│   │   ├── ......
│   │   └── ......
│   └── noisy
│       ├── F05_440C0202_BUS.wav
│       ├── F05_440C0202_CAF.wav
│       ├── ......
│       └── ......
├── training_dataset
│   ├── clean_speech
│   │   ├── 011_011C0201_PED.wav
│   │   ├── 011_011C0202_PED.wav
│   │   ├── ......
│   │   └── ......
│   └── noise_segment_all
│       ├── BGD_150203_010_CAF_0.wav
│       ├── BGD_150203_010_CAF_1.wav
│       ├── ......
│       └── ......
└── validation_dataset
    ├── clean
    │   ├── F01_050C0103_BUS.wav
    │   ├── F01_050C0103_CAF.wav
    │   ├── ......
    │   └── ......
    └── noisy
        ├── F01_050C0103_BUS.wav
        ├── F01_050C0103_CAF.wav
        ├── ......
        └── ......

**Comment by Yang-yujie** [comment]
组织的数据集结构如下：
![dataset_structure](https://github.com/Audio-WestlakeU/McNet/assets/52712560/277240fd-d554-4d25-8548-4fca659a523f)

**Comment by XiangzhuKong** [comment]
非常感谢~！：）
